# Site settings
title: Happy Birthday Matt!
#email: your-email@domain.com
description: A little corner on the web for your Birthday.
#baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mattdilbeck.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
